import { L } from "../helpers";
import type { AcademyCategory } from "../types";

export const blackpebbleFeaturesCategory: AcademyCategory = {
  id: "blackpebble-features",
  title: "BlackPebble Features",
  icon: "sparkles",
  lessons: [
    L(
      "trading-desk",
      "Trading Desk and Paper Trading",
      "The Trading Desk is where you paper trade Solana tokens at live market prices using simulated funds. Paper trading lets you practice strategies without real risk. Orders, TP, SL, and fills are all simulated.",
      "Practice trading ideas and build a track record before considering real capital.",
      { aliases: ["paper trading", "trading desk"], related: { label: "Trading Desk", path: "/" } },
    ),
    L(
      "markets",
      "Markets Explorer",
      "Markets shows trending tokens, recent launches, and high-activity pairs. Quick filters help surface opportunities. Each token card links to the Trading Desk for immediate paper trading.",
      "Use Markets to discover tokens and jump into research or trades.",
      { related: { label: "Markets", path: "/markets" } },
    ),
    L(
      "portfolio",
      "Portfolio",
      "Portfolio displays your open positions, trade history, equity over time, and performance metrics. Paper and perp positions appear together with real-time simulated PnL.",
      "Reviewing portfolio data reveals patterns in your trading behavior.",
      { aliases: ["positions", "trade history", "equity chart"], related: { label: "Portfolio", path: "/portfolio" } },
    ),
    L(
      "trader-dna",
      "Trader DNA",
      "Trader DNA summarizes your trading patterns: hold time, size habits, entry timing, and win tendencies. It helps identify strengths and weaknesses.",
      "Use DNA insights to refine strategy and notice blind spots.",
      { aliases: ["DNA", "trading patterns"], related: { label: "Trading Intelligence", path: "/utilities/trading-analysis" } },
    ),
    L(
      "order-tools",
      "Order Tools",
      "BlackPebble supports market orders, buy limits, take profit (TP), stop loss (SL), and multi-target TP. Orders execute against simulated balances at live prices.",
      "Automated exits help enforce discipline when memecoins move fast.",
      { aliases: ["TP", "SL", "limit", "multi TP"], related: { label: "Trading Desk", path: "/" } },
    ),
    L(
      "paper-perps",
      "Paper Perps",
      "Paper perps let you practice leveraged long and short positions on memecoins using simulated margin. Liquidations, funding, and PnL are all simulated.",
      "Perps amplify gains and losses. Use paper perps to learn leverage mechanics risk-free.",
      { aliases: ["perps", "leverage"], related: { label: "Trading Desk", path: "/" }, callout: { type: "advanced", text: "Paper perps are simulated. No real margin or liquidation risk." } },
    ),
    L(
      "trading-journal",
      "Trading Journal",
      "The Trading Journal stores notes, screenshots, and reflections for each trade. Reviewing journal entries surfaces emotional and process patterns.",
      "Journaling improves learning from both wins and losses.",
      { related: { label: "Trading Journal", path: "/utilities/journal" } },
    ),
    L(
      "watchlists",
      "Watchlists",
      "Watchlists let you track tokens without holding a position. Quick access to price, volume, and market cap changes helps monitor opportunities.",
      "Build focused watchlists instead of drowning in random discoveries.",
      { related: { label: "Markets", path: "/markets" } },
    ),
    L(
      "public-profiles",
      "Public Profiles",
      "Public profiles display portfolio stats, calls, thesis posts, achievements, and badges. Followers can track your activity. You control what is visible.",
      "Build reputation by sharing insights and demonstrating skill over time.",
      { aliases: ["profile", "followers", "following"], related: { label: "Leaderboard", path: "/leaderboard" } },
    ),
    L(
      "calls-and-thesis",
      "Calls and Thesis Posts",
      "A call is a public trade recommendation with a verified entry snapshot. A thesis post explains your reasoning. Both build reputation when they perform well.",
      "Posting calls creates accountability. ATH from call shows your best outcomes.",
      { aliases: ["call", "thesis"], related: { label: "Feed", path: "/feed" }, callout: { type: "why", text: "Verified calls are timestamped and cannot be faked after the fact." } },
    ),
    L(
      "feed-and-reactions",
      "Feed and Reactions",
      "The Feed shows community activity: trades, calls, achievements, and milestones. Reactions let you respond to activity. Follow traders to personalize your feed.",
      "Use the feed to discover active traders and see what the community is watching.",
      { aliases: ["feed", "reactions"], related: { label: "Feed", path: "/feed" } },
    ),
    L(
      "reputation-metrics",
      "Reputation Metrics",
      "Trust Score summarizes call and trading quality. BP Score reflects overall platform engagement. Rank compares you to other traders. Tier groups traders by performance and activity.",
      "Reputation metrics help surface skilled traders and build credibility.",
      { aliases: ["trust score", "BP score", "rank", "tier"], related: { label: "Leaderboard", path: "/leaderboard" } },
    ),
    L(
      "achievements",
      "Achievements",
      "Achievements reward milestones like first call, first 10x, or journaling streaks. Unlocked achievements appear on your profile and sometimes on the feed.",
      "Achievements gamify progress and highlight notable accomplishments.",
      { related: { label: "Portfolio", path: "/portfolio" } },
    ),
    L(
      "leaderboards",
      "Leaderboards",
      "Leaderboards rank traders by PnL, call performance, trust score, and other metrics. Seasons reset rankings periodically for fresh competition.",
      "Leaderboards surface top performers for discovery and inspiration.",
      { related: { label: "Leaderboard", path: "/leaderboard" } },
    ),
    L(
      "trading-intelligence",
      "Trading Intelligence",
      "Trading Intelligence analyzes your trading behavior with pattern detection, edge analysis, and improvement suggestions. All analysis is read-only.",
      "Use intelligence reports to find blind spots and refine your strategy.",
      { aliases: ["intelligence", "analysis"], related: { label: "Trading Intelligence", path: "/utilities/trading-analysis" } },
    ),
    L(
      "wallet-utilities",
      "Wallet Utilities",
      "Wallet Cleanup finds empty token accounts, spam NFTs, and dust. SOL Recovery retrieves rent deposits. Both require real transaction signatures after your review.",
      "Clean up your wallet to recover locked SOL and remove clutter.",
      { aliases: ["cleanup", "SOL recovery"], related: { label: "Wallet Cleanup", path: "/utilities/wallet-cleaner" }, callout: { type: "safety", text: "Wallet utilities involve real transactions. Review before signing." } },
    ),
    L(
      "community-campaigns",
      "Community Campaigns",
      "Community Campaigns let organizers collect contributions toward shared goals with transparent ledgers and escrow. Contributors can track progress and outcomes.",
      "Campaigns enable coordinated community funding with accountability.",
      { aliases: ["campaigns", "funding"], related: { label: "Community Campaigns", path: "/campaigns" }, callout: { type: "advanced", text: "Campaign features are evolving. Check current documentation for exact behavior." } },
    ),
    L(
      "notifications",
      "Notifications",
      "Notifications alert you to order fills, achievements, reactions, and important activity. The notification center collects recent alerts for easy review.",
      "Check notifications to stay current on your activity and community engagement.",
      { aliases: ["alerts", "notification center"] },
    ),
    L(
      "wallet-safety-page",
      "Wallet Safety",
      "The Wallet Safety page explains what is simulated, what is read-only, and what requires signatures. It clarifies BlackPebble's security model.",
      "Review Wallet Safety before using wallet tools for the first time.",
      { related: { label: "Wallet Safety", path: "/safety" } },
    ),
  ],
};
