import { L } from "../helpers";
import type { AcademyCategory } from "../types";

export const cryptoSlangCategory: AcademyCategory = {
  id: "crypto-slang",
  title: "Common Crypto and Degen Slang",
  icon: "message",
  lessons: [
    L("degen", "Degen", "Degen (degenerate) describes high-risk, high-reward trading style. Used both proudly and cautiously.", ""),
    L("ape", "Ape/Aping", "Aping means buying quickly without much research, usually in a rush to catch early price action.", ""),
    L("fomo", "FOMO", "Fear of missing out. The urge to buy because something is pumping, often leading to bad entries.", ""),
    L("fud", "FUD", "Fear, uncertainty, and doubt. Negative sentiment, sometimes real concerns, sometimes manipulation.", ""),
    L("diamond-hands", "Diamond Hands", "Holding through volatility without selling. Often used to encourage not panic selling.", ""),
    L("paper-hands", "Paper Hands", "Selling at the first sign of trouble. The opposite of diamond hands.", ""),
    L("ngmi", "NGMI", "Not gonna make it. Often used to mock poor decisions or pessimism.", ""),
    L("wagmi", "WAGMI", "We're all gonna make it. Optimistic community rallying cry.", ""),
    L("gm", "GM", "Good morning. A friendly crypto Twitter greeting.", ""),
    L("ser", "Ser/Fren", "Playful spellings of sir or friend, used casually in crypto communities.", ""),
    L("rekt", "Rekt", "Wrecked. Lost significant money, often from a bad trade or rug.", ""),
    L("bag", "Bag", "A holding of a token. Heavy bags mean you are stuck holding a losing position.", ""),
    L("moon", "Moon/Mooning", "Price rising dramatically. To the moon suggests extreme gains.", ""),
    L("pump", "Pump", "Rapid price increase, sometimes organic, sometimes manipulated.", ""),
    L("dump", "Dump", "Rapid price decline, often from large sells or coordinated exits.", ""),
    L("pump-and-dump", "Pump and Dump", "Coordinated scheme to inflate price then sell on latecomers.", ""),
    L("whale", "Whale", "A large holder who can move markets with their trades.", ""),
    L("alpha", "Alpha", "Valuable insider information or early knowledge about an opportunity.", ""),
    L("nfa", "NFA", "Not financial advice. Disclaimer used when sharing opinions.", ""),
    L("dyor", "DYOR", "Do your own research. Reminder to verify claims before acting.", ""),
    L("based", "Based", "Admirable, cool, or unapologetically authentic.", ""),
    L("chad", "Chad", "Someone making bold, confident plays. Often used admiringly.", ""),
    L("cope", "Cope/Copium", "Rationalizing losses or bad decisions to feel better.", ""),
    L("larp", "LARP", "Live-action role play. Pretending to be something you are not, like faking success.", ""),
    L("lfg", "LFG", "Let's go. Hype phrase for excitement or momentum.", ""),
    L("bluechip", "Blue Chip", "Established, large-cap tokens considered relatively safer.", ""),
    L("shitcoin", "Shitcoin", "Low-quality token with little utility. Used both negatively and affectionately.", ""),
    L("jeet", "Jeet", "Someone who sells early, often at a loss, missing larger gains.", ""),
    L("send-it", "Send It", "Go all in. Take the risk without hesitation.", ""),
    L("exit-liquidity", "Exit Liquidity", "New buyers who provide liquidity for insiders to sell into. Often used as a warning.", ""),
  ],
};
